import Head from "next/head";
import Header from "../../components/Header";
import RankingResult from "../../components/RankingResult";
import javlibData from "../../config/javlibData.json";
import rankingMovie from "../../config/rankingMovie.json";
import rankingActress from "../../config/rankingActress.json";
import rankingnewBie from "../../config/rankingnewBie.json";
import rankingClassicMovie from "../../config/rankingClassicMovie.json";

function index() {
  return (
    <div className="">
      <Head>
        <title>My JavLib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header collections={javlibData} />

      <main className="mx-auto max-w-screen">
        <RankingResult
          collections={rankingMovie}
          actress={rankingActress}
          newBie={rankingnewBie}
          royal={rankingClassicMovie}
        />
      </main>
    </div>
  );
}

export default index;
