import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Header from "../../components/Header";
import ResultList from "../../components/ResultList";
import javlibData from "../../config/javlibData.json";

function index() {
  const router = useRouter();
  const [searchTerm, setSearchTerm] = useState("");
  const [searchResults, setSearchResults] = useState([]);
  const [showResults, setShowResults] = useState(false);

  const [searchPublisher, setSearchPublisher] = useState(false);
  const [searchActress, setSearchActress] = useState(false);
  const [searchKeywords, setSearchKeywords] = useState(false);

  const handleSearch = (e) => {
    setSearchTerm(e.target.value);

    setSearchResults(
      javlibData.filter((collection) =>
        collection.code.includes(searchTerm.toLocaleUpperCase())
      )
    );
  };

  useEffect(() => {
    setSearchResults(
      javlibData.filter((collection) =>
        collection.code.includes(searchTerm.toLocaleUpperCase())
      )
    );
  }, [searchTerm, javlibData]);

  return (
    <div>
      <Head>
        <title>My JavLib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center p-4 space-x-10 sticky top-0 z-50 shadow-lg">
        <div className=" cursor-pointer" onClick={() => router.push("/")}>
          <h1 className="text-lg">My JavLib</h1>
        </div>
        <div className=" hidden sm:flex relative items-center rounded-md h-10 flex-grow cursor-pointer">
          <input
            className={` font-bold tracking-widest bg-gradient-to-l text-gray-800 from-[#06202A] p-2 px-5 h-full w-full flex-grow rounded flex-shrink rounded-l-md focus:outline-none
             `}
            value={searchTerm}
            onChange={handleSearch}
          />
        </div>
        <div className="flex space-x-6 outline-none">
          <div
            onClick={() => router.push("/filter")}
            className="w-full outline-none hover:bg-gray-500 p-4 rounded-2xl cursor-pointer"
          >
            Filter
          </div>
          <div className="w-full outline-none    hover:bg-gray-500 p-4 rounded-2xl cursor-pointer">
            Add
          </div>
        </div>
      </div>

      <main className="mx-auto max-w-screen">
        <div className="px-5 my-10 grid grid-flow-row-dense md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {searchResults.map((collection) => (
            <ResultList
              id={collection.id}
              code={collection.code}
              image={collection.image}
              name={collection.name}
              title={collection.title}
              keywords={collection.keywords}
              publisher={collection.publisher}
            />
          ))}
        </div>
      </main>
    </div>
  );
}

export default index;
