import Head from "next/head";

import { useEffect } from "react";

import Header from "../components/Header";
import Result from "../components/Result";
import { useDispatch, useSelector } from "react-redux";
import { addMovie } from "../features/movieSlice";
import { resetGrid } from "../features/gridSlice";
import Banner from "../components/Banner";
import Reveal from "react-reveal/Reveal";

import javlibData from "../config/javlibData.json";

export default function Home({ movies }) {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(resetGrid());
    dispatch(addMovie(movies));
  }, [movies]);

  return (
    <div className="">
      <Head>
        <title>My JavLib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header collections={movies} />

      <main className="mx-auto max-w-screen">
        <Reveal effect="fadeInUp">
          <Result collections={movies} />
        </Reveal>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const ref = javlibData;

  const movieRes = await ref;

  return {
    props: {
      movies: movieRes,
    },
  };
}
