import Head from "next/head";

import { useEffect } from "react";

import Header from "../components/Header";
import Result from "../components/Result";
import { useDispatch, useSelector } from "react-redux";
import { addMovie } from "../features/movieSlice";

import javlibData from "../config/javlibData.json";

export default function Home(results) {
  const dispatch = useDispatch();

  console.log("javlibDatas>>>", results);

  useEffect(() => {
    dispatch(addMovie(javlibData));
  }, [javlibData]);

  return (
    <div className="">
      <Head>
        <title>My JavLib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header collections={javlibData} />

      <main className="mx-auto max-w-screen">
        <Result collections={javlibData} />
      </main>
    </div>
  );
}
