import Header from "../components/Header";
import Head from "next/head";
import javlibData from "../config/javlibData.json";
import Banner from "../components/Banner";

function random({ movies }) {
  return (
    <div>
      <Head>
        <title>My JavLib || Random</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header collections={movies} />
      <Banner />
    </div>
  );
}

export default random;

export async function getServerSideProps(context) {
  const ref = javlibData;

  const movieRes = await ref;

  return {
    props: {
      movies: movieRes,
    },
  };
}
