import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "../components/Header";
import javlibData from "../config/javlibData.json";
import s1logo from "../images/s1logo.png";
import iplogo from "../images/iplogo.png";
import madonnalogo from "../images/madonnalogo.png";
import attackerslogo from "../images/attackerslogo.png";
import moodyzlogo from "../images/moodyzlogo.gif";
import tameikegoro from "../images/taamekalogo.png";

function website() {
  const webbpage = [
    {
      publisher: "S1",
      publisherImg: `${s1logo}`,
      url: "https://www.s1s1s1.com/top/",
    },
    {
      publisher: "IDEA POCKET",
      publisherImg: `${iplogo}`,
      url: "https://www.ideapocket.com/top/",
    },
    {
      publisher: "MADONNA",
      publisherImg: `${madonnalogo.png}`,
      url: "https://www.madonna-av.com/top/",
    },
    {
      publisher: "ATTACKERS",
      publisherImg: `${attackerslogo}`,
      url: "https://www.attackers.net/top/",
    },
    {
      publisher: "MOODYZ",
      publisherImg: `${moodyzlogo}`,
      url: "https://www.moodyz.com/top/",
    },
    {
      publisher: "溜池",
      publisherImg: `${tameikegoro}`,
      url: "https://www.tameikegoro.jp/top/",
    },
  ];

  https: return (
    <div>
      <Head>
        <title>My JavLib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header collections={javlibData} />
      <main className="mx-auto max-w-screen">
        <div className="px-5 my-10 grid grid-flow-row-dense md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          <div className="relative flex flex-col m-5 bg-white z-30 p-10 shadow-lg">
            <Link href="https://www.s1s1s1.com/top/">
              <Image
                src={s1logo}
                height={300}
                width={300}
                objectFit="contain"
                className={` cursor-pointer  transition duration-300 ease-in transform sm:hover:scale-125`}
              />
            </Link>
          </div>
          <div className="relative flex flex-col m-5 bg-white z-30 p-10 shadow-lg">
            <Link href="https://www.ideapocket.com/top/">
              <Image
                src={iplogo}
                height={300}
                width={300}
                objectFit="contain"
                className={` cursor-pointer  transition duration-300 ease-in transform sm:hover:scale-125`}
              />
            </Link>
          </div>
          <div className="relative flex flex-col m-5 bg-white z-30 p-10 shadow-lg">
            <Link href="https://www.madonna-av.com/top/">
              <Image
                src={madonnalogo}
                height={300}
                width={300}
                objectFit="contain"
                className={` cursor-pointer  transition duration-300 ease-in transform sm:hover:scale-125`}
              />
            </Link>
          </div>
          <div className="relative flex flex-col m-5 bg-white z-30 p-10 shadow-lg">
            <Link href="https://www.attackers.net/top/">
              <Image
                src={attackerslogo}
                height={300}
                width={300}
                objectFit="contain"
                className={` cursor-pointer  transition duration-300 ease-in transform sm:hover:scale-125`}
              />
            </Link>
          </div>
          <div className="relative flex flex-col m-5 bg-white z-30 p-10 shadow-lg">
            <Link href="https://www.moodyz.com/top/">
              <Image
                src={moodyzlogo}
                height={300}
                width={300}
                objectFit="contain"
                className={` cursor-pointer  transition duration-300 ease-in transform sm:hover:scale-125`}
              />
            </Link>
          </div>
          <div className="relative flex flex-col m-5 bg-white z-30 p-10 shadow-lg">
            <Link href="https://www.tameikegoro.jp/top/">
              <Image
                src={tameikegoro}
                height={300}
                width={300}
                objectFit="contain"
                className={` cursor-pointer  transition duration-300 ease-in transform sm:hover:scale-125`}
              />
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}

export default website;
